@url = https://{{domain}}.atlassian.net/rest/api/3
@authHeader = Basic {{base64String}}

GET {{url}}/search
Authorization: {{authHeader}}

###

POST {{url}}/issue
Authorization: {{authHeader}}
Content-Type: application/json

{
  "fields": {
    "issuetype": {
      "id": "10002"
    },
    "project": {
      "id": "10000"
    },
    "summary": "aaa"
  }
}
